# default application Config!
---
server:
  port: 8080
  servlet:
    context-path: /koumanafamaPlayer
---
spring:
  profiles: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
datasource:
#  sampleapp:
#    url: jdbc:mysql://localhost:3306/websystique
#    username: myuser
#    password: mypassword
#    driverClassName: com.mysql.jdbc.Driver
#    defaultSchema:
#    maxPoolSize: 20
#    hibernate:
#      hbm2ddl.method: update
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect
  sampleapp:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

koumanafama:
  media:
    url:     'https://d5hbr1ssw3zww.cloudfront.net/assets/audio/'
    uploads: 'https://d5hbr1ssw3zww.cloudfront.net/assets'
  aws:
    s3:
      bucket-name: 'koumanafama-366550255936-us-east-1-dev-files'
      region: 'us-east-1'
    cloudfront:
      domain: 'https://d5hbr1ssw3zww.cloudfront.net'