---
server:
  port: 8081
  servlet:
    context-path: /djago
---
spring:
  profiles: local, default, mod
datasource:
  sampleapp:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:~/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/djago
    username: ENC(Zeg2RRS9SYlvg6r5DyI+tQmv3s40Wl5WdCgqb3kV6BzoH2NWMfILfBF3myY4h5EH)
    password: ENC(u62yZ/SFY2r6vDN7Y6OA00aHKGlk+a+8aryxek3+wyo8LBMBLmFlkeS6pwcW2xSm)
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect